import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { WarehouseConfig, LayoutItem } from '../types';

// Helper to calculate volume of an item in m3
const getItemVolumeCapacity = (item: LayoutItem, levelHeight: number): number => {
    const widthM = item.width / 100;
    const lengthM = item.height / 100; // item.height is length on 2D plane
    const heightM = (item.depth || (levelHeight - 50)) / 100;
    return parseFloat((widthM * lengthM * heightM).toFixed(2));
};

export const generateWarehouseReport = (config: WarehouseConfig) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;

  // --- Branding & Header Helper ---
  const drawHeader = (yOffset: number = 0) => {
      // Logo Construction (Approximation of Writer Relocations Diamond)
      const logoSize = 15;
      const logoX = 15;
      const logoY = 15 + yOffset;

      // Black Diamond Base
      doc.setFillColor(17, 17, 17); // #111
      doc.triangle(
          logoX, logoY + logoSize/2, 
          logoX + logoSize/2, logoY, 
          logoX + logoSize, logoY + logoSize/2
      );
      doc.triangle(
          logoX, logoY + logoSize/2, 
          logoX + logoSize/2, logoY + logoSize, 
          logoX + logoSize, logoY + logoSize/2
      );

      // Yellow Accent Stripe
      doc.setFillColor(255, 204, 0); // #FFCC00
      doc.triangle(
        logoX + logoSize/2, logoY,
        logoX + logoSize * 0.7, logoY + logoSize * 0.2,
        logoX + logoSize/2, logoY + logoSize
      );

      // Company Name
      doc.setFont("times", "bold");
      doc.setFontSize(18);
      doc.setTextColor(50, 50, 50);
      doc.text("WRITER", logoX + logoSize + 5, logoY + 8);
      
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8);
      doc.setTextColor(200, 0, 0); // Red
      doc.text("RELOCATIONS", logoX + logoSize + 5, logoY + 13);
      
      doc.setTextColor(100, 100, 100);
      doc.text("PREMIUM LOGISTICS SERVICES", logoX + logoSize + 30, logoY + 13);

      // Report Title
      doc.setFont("helvetica", "bold");
      doc.setFontSize(22);
      doc.setTextColor(30, 41, 59);
      doc.text("Warehouse Inventory Report", pageWidth - 15, logoY + 10, { align: 'right' });
      
      doc.setDrawColor(200, 200, 200);
      doc.line(15, logoY + 20, pageWidth - 15, logoY + 20);
  };

  const drawFooter = (pageNumber: number) => {
      const footerY = pageHeight - 20;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(100, 100, 100);
      
      const address = "P.O. Box 34892\nDubai, UAE\nPhone: (971) 4 340 8814   Fax: (971) 4 340 8815";
      doc.text(address, pageWidth / 2, footerY, { align: 'center', lineHeightFactor: 1.5 });
      
      doc.text(`Generated by: Writer Planner Pro - ${new Date().toLocaleDateString()}`, 15, pageHeight - 10);
      doc.text(`Page ${pageNumber}`, pageWidth - 15, pageHeight - 10, { align: 'right' });
  };

  // --- Initial Page ---
  drawHeader();

  let currentY = 50;

  // Project Info
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text(`Project: ${config.name}`, 15, currentY);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 15, currentY + 6);
  doc.text(`Total Area: ${config.dimensions.totalArea} m²`, 15, currentY + 12);

  currentY += 25;

  // --- Iterate Levels ---
  config.levels.forEach((level, index) => {
      // Add new page if not enough space for header + some rows
      if (currentY > pageHeight - 60) {
          doc.addPage();
          drawHeader();
          currentY = 50;
      }

      // Filter storage items
      const storageItems = level.items.filter(i => 
        ['rack', 'open_cabin', 'open_space_storage'].includes(i.type)
      );

      // Calculate Level Stats
      const totalLevelCapacityM3 = storageItems.reduce((sum, item) => sum + getItemVolumeCapacity(item, level.height), 0);
      const totalOccupiedM3 = storageItems.reduce((sum, item) => sum + (item.rackDetails?.volumeOccupied || 0), 0);
      const totalAvailableM3 = totalLevelCapacityM3 - totalOccupiedM3;
      const occupancyRate = totalLevelCapacityM3 > 0 ? (totalOccupiedM3 / totalLevelCapacityM3) * 100 : 0;

      // Level Header
      doc.setFillColor(241, 245, 249); // slate-100
      doc.rect(15, currentY, pageWidth - 30, 20, 'F');
      
      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.setTextColor(0, 0, 0);
      doc.text(`Floor: ${level.name}`, 20, currentY + 8);
      
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.text(`Total Volume: ${totalLevelCapacityM3.toFixed(2)} m³  |  Occupied: ${totalOccupiedM3.toFixed(2)} m³  |  Available: ${totalAvailableM3.toFixed(2)} m³`, 20, currentY + 15);
      
      currentY += 25;

      if (storageItems.length === 0) {
          doc.setFont("helvetica", "italic");
          doc.text("No storage units defined on this floor.", 20, currentY);
          currentY += 15;
      } else {
          // Prepare Table Data
          const tableData = storageItems.flatMap(item => {
              const details = item.rackDetails;
              const maxVol = getItemVolumeCapacity(item, level.height);
              const usedVol = details?.volumeOccupied || 0;
              const leftVol = maxVol - usedVol;

              if (details?.jobs && details.jobs.length > 0) {
                  return details.jobs.map((job, jIdx) => [
                      jIdx === 0 ? (item.label || item.id.split('-').pop()) : '', // Only show ID on first row of item
                      job.shipperName || '-',
                      job.jobNumber ? `AE ${job.jobNumber}` : '-',
                      (job.status || 'Active').toUpperCase(),
                      `${job.inDate || '-'} / ${job.outDate || '-'}`,
                      job.paymentCycle || '-',
                      `${(job.pricePerMonth || 0).toFixed(2)} AED`,
                      jIdx === 0 ? `${usedVol} / ${leftVol.toFixed(2)}` : ''
                  ]);
              }

              return [[
                  item.label || item.id.split('-').pop(), // Unit ID
                  details?.shipperName || '-',
                  details?.jobNumber ? `AE ${details.jobNumber}` : '-',
                  (details?.status || 'Available').toUpperCase(),
                  `${details?.inDate || '-'} / ${details?.outDate || '-'}`,
                  '-',
                  `${(details?.price || 0).toFixed(2)} AED`,
                  `${usedVol} / ${leftVol.toFixed(2)}` // m3 Used / Left
              ]];
          });

          autoTable(doc, {
              startY: currentY,
              head: [['Unit ID', 'Shipper Name', 'Job #', 'Status', 'In / Out Date', 'Cycle', 'Price', 'm³ (Used/Left)']],
              body: tableData,
              theme: 'grid',
              headStyles: { fillColor: [17, 17, 17], textColor: [255, 204, 0], fontSize: 7 },
              bodyStyles: { fontSize: 7 },
              margin: { left: 15, right: 15 },
              didDrawPage: (data) => {
                  // Redraw header on new pages if table breaks
                  if (data.pageNumber > 1 && data.cursor.y === data.settings.startY) {
                       drawHeader();
                       // Footer handled by global loop below, but simple headers need care
                  }
              }
          });

          // Update Y for next section
          currentY = (doc as any).lastAutoTable.finalY + 15;
      }
  });

  // Add Footers to all pages
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    drawFooter(i);
  }

  doc.save(`${config.name.replace(/\s+/g, '_')}_Report.pdf`);
};
